accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name = 'register'),
    path('profil/', views.profil, name='profil'),
    path('modifprofil/<id>', views.modifprofil, name = 'modifprofil'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', redirect_authenticated_user = True), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html', next_page='pages:home'), name = 'logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
]

note/urls.py
from django.urls import path

from .views import NoteDetailView, ViewNote, AddNoteView, ModifNoteView, DeleteNote


urlpatterns = [
    path('', ViewNote.as_view(), name = 'note'),
    path('detail_note/<int:pk>', NoteDetailView.as_view(), name = 'detail_note'),
    path('add_note/', AddNoteView.as_view(), name = 'add_note'),
    path('detail_note/edit/<int:pk>', ModifNoteView.as_view(), name = 'modif_note'),
    path('remove/<int:pk>', DeleteNote.as_view(), name = 'delete_note'),
    ]

pages/urls.py
from django.urls import path, include

from .views import HomePageView, ContactPageView

app_name = 'pages'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext as _
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class CustomUser(AbstractUser):
    date_of_birth = models.DateField(_("date of birth"), blank=True, null=True)
    street_number=models.IntegerField(_("street number"), blank=True, null=True)
    street = models.CharField(_("street"), max_length=500, blank=True, null=True)
    zipcode = models.IntegerField(_("zip code"), blank=True, null=True)
    town = models.CharField(_("town"), max_length=200, blank=True, null=True)
    mobile = PhoneNumberField(_("mobile"), blank=True, null=True)

    class Meta:
        ordering = ['last_name']
    
    def __str__(self):
        return f"{self.username}: {self.first_name} {self.last_name} {self.date_of_birth} {self.street_number} {self.street} {self.zipcode} {self.town} {self.mobile}"

contact/models.py
from django.db import models

# Create your models here.

note/models.py
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from accounts.models import CustomUser
from django.urls import reverse
from datetime import datetime, date



class Note(models.Model):
    title =  models.CharField(max_length=255)
    content = RichTextField(blank=True, null=True)
    creation_date = models.DateField(auto_now_add=True)
    image_file = models.ImageField(blank=True, null=True, upload_to="media/")
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("detail_note", kwargs={"pk": self.pk})
    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(forms.ModelForm):

    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
    label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ['id', 'username', 'first_name', 'last_name', 'email','date_of_birth', 'street', 'street_number', 'street', 'zipcode', 'town', 'mobile']
        widgets = {
            "username": forms.TextInput(attrs={
                "class": "registration-username", 
                "placeholder": "Entrez votre nom d'utilisateur"
                }), 
            "first_name": forms.TextInput(attrs={
                "class": "registration-first_name", 
                "placeholder": "Entrez votre prénom"
                }),            
            "last_name": forms.TextInput(attrs={
                "class": "registration-last_name", 
                "placeholder": "Entrez votre nom de famille"
                }),
            "email": forms.EmailInput(attrs={
                "class": "registration-email", 
                "placeholder": "Entrez votre email"
                }),
            "date_of_birth": forms.DateInput(attrs={
                "class": "registration-date_of_birth",
                "type": "date"
                }),
            
        }
    
class CustomUserChangeForm(forms.ModelForm):
   class Meta:
        model = CustomUser
        fields = ['id', 'username', 'first_name', 'last_name', 'email', 'date_of_birth', 'street_number', 'street', 'zipcode', 'town', 'mobile']
    

note/forms.py
from django import forms
from .models import Note

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ('title', 'content', 'image_file')
        
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, CreateView
from .forms import forms
from .models import CustomUser

from .forms import CustomUserCreationForm


def register(request):
    if request.user.is_authenticated:
        return redirect('pages:home')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)

        if form.is_valid():
            form.save()
        return render(request, 'accounts:profil.html')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/register.html', context)


def modifprofil(request, id):
    user = get_object_or_404(CustomUser, id=id)
    form = CustomUserCreationForm(request.POST or None, instance=user)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect('accounts:profil')
    
    return render(request, 'accounts/modifprofil.html', {"form":form})


def profil(request):
    if request.method == 'Request':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/profil.html', context)

contact/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.conf import settings

def fooview(request):
    
    if request.method=="POST":
        name=request.POST.get('name')
        email=request.POST.get('email')
        subject=request.POST.get('subject')
        message=request.POST.get('message')
        send_mail(subject= subject,message= message,from_email=settings.DEFAULT_FROM_EMAIL,recipient_list = [email],fail_silently  = True,)
        
        return redirect('fooview')

    return render(request,'baar.html',{})

note/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView

from .models import Note
from.forms import NoteForm

# from django.core.paginator import Paginator

class ViewNote(ListView):
    model = Note
    template_name = 'note/note.html'
    paginate_by = 6
    
    # # ordering = ['-id']

class AddNoteView(CreateView):
    model = Note
    form_class = NoteForm
    template_name = "note/add_note.html"
    
    
class NoteDetailView(DetailView):
    model = Note
    template_name = 'note/detail_note.html'
    

class ModifNoteView(UpdateView):
    model = Note
    template_name = "note/modif_note.html"
    form_class = NoteForm
    
    
class DeleteNote(DeleteView):
    model = Note
    template_name = 'note/delete_note.html'
    success_url = reverse_lazy('note')

pages/views.py
from django.views.generic import TemplateView
from django.http import HttpResponse
from datetime import datetime


class HomePageView(TemplateView):
    template_name = 'pages/home.html'
   
    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['myDate'] = datetime.now()
        return context


class ContactPageView(TemplateView):
    template_name = 'pages/contact.html'
        

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}NotePad | Login{% endblock title %}
{% block content %}

 <style>
    table {
      margin: 1em;
      width: 100%;
      border: 3px solid bleue;
      padding: 10px;
    }

    input{
        margin: 1em;
    }

</style>


<div class= "form-group">
        <table>
            <form  method='post'>    
                {% csrf_token %}
                    {{ form.as_table}}
            </table>
            <input type="submit" class="btn btn-outline-info mb-2" value='Login'</input>
</div>
{% comment %} </header> {% endcomment %}

{% endblock content %}

accounts/templates/accounts/modifprofil.html
{% extends 'base.html' %}
{% load static %}
{% block title %}NotePad | ModifProfil{% endblock title %}

{% block content %}
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<link rel="stylesheet" href="{% static './css/register.css' %}">

    <div class= "form-group">
    <table>
    <ber>
        <form method='POST'>
            {% csrf_token %}
            {{ form.as_table}}
         
        </table>
        <button class="btn btn-primary " type= "submit" >Mettre à jour</button>
    </div>

{% endblock content %}

accounts/templates/accounts/profil.html
{% extends 'base.html' %}
{% load static %}

{% block title %}NotePad | Profil{% endblock title %}

{% block content %}
<link rel="stylesheet" href="{% static './css/profil.css' %}">
<div class="myprofil">
  <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
    <div class="row">
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="d-flex flex-column align-items-center text-center">
              <img src="{% static 'images/profil.jpg' %}" alt="image" class="rounded-circle" width="150">
              <div class="mt-3">
                <h4>{{ user.username|upper}}</h4>
                <p class="text-muted font-size-sm">
                  {% if user.street_number != None %} 
                    {{user.street_number}}, 
                  {% endif %} 
                  {% if user.street != None %} 
                    {{user.street|capfirst }} 
                  {% endif %}
                </p>
                <p class="text-muted font-size-sm">
                  {% if user.zipcode != None %}
                    {{user.zipcode}} - 
                  {% endif %}
                  {% if user.town != None %}
                    {{user.town|upper}} 
                  {% endif %}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="card mb-3">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Full Name</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                {{user.first_name}}, {{user.last_name|upper}}
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Email</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                {{user.email|lower}}
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">date of birth</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                {{user.date_of_birth}}
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Mobile</h6>
              </div>
              <div class="col-sm-9 text-secondary">
                {{user.mobile}}
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-12">
               <a class="btn btn-primary " href="{% url 'accounts:modifprofil' id=user.id %}">Modifier</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}NotePad | Register{% endblock title %}

{% block content %}
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<link rel="stylesheet" href="{% static './css/register.css' %}">

    <div class= "form-group">
    <table>
    <ber>
        <form method='POST'>
            {% csrf_token %}
            {{ form.as_table}}
         
        </table>
        <button class="btn btn-primary " type= "submit" >M'inscrire</button>
    </div>

{% endblock content %}

note/templates/note/add_note.html
{% extends 'base.html' %}
{% block title %}NotePad | Nouvelle Note{% endblock title %}
{% block content %}

<div class="container">
    <div class="card mb-3 shadow">
        <div class="card-body">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.media}}
                {{ form.as_p }}
                <button class="btn btn-primary btn-sm" > Enregistrer</button>
            </form>
        </div>  
    </div>
</div>

{% endblock content%}

note/templates/note/delete_note.html
{% extends 'base.html' %}
{% block title %}NotePad | Supprimer note{% endblock title %}
{% block content %}

<div class="container">
    <div class="card mb-3 shadow">
        <div class="card-body">
            <h3> Suppression de la Note : {{ note.title }}
                <br/>
                <hr>
                <br/>
            <form method="POST" >
                {% csrf_token %}
                {{ note.content }}
                <hr>
                <strong >Es-tu sure de vouloir la supprimer ??!!</strong> <br/><br/>
                <button class="btn btn-primary btn-sm" >Supprimer la Note</button>
            </form>
        </div>  
    </div>
</div>

{% endblock content%}

note/templates/note/detail_note.html
{% extends 'base.html' %}
{% block title %}NotePad | Note{% endblock title %}
{% block content %}

<hr>
<h1><center>{{note.title | upper}}   <h3>Créée le : {{note.creation_date | date:'d F Y'}}</h3></center></h1>
<hr>
<div class="container">
    <div class="card mb-3 shadow">
        <div class="card-body">
            <h2><center>{{note.title}}</center></h2>
        <hr>
        {% if note.image_file %}
            <img src = "{{note.image_file.url}}" width="500" height="500" class="center">
        {% endif%}
            {{note.content | safe}}
        
        <hr>
            <a href="{% url 'note' %}" class="card-link"> Retour</a> 
            <a href="{% url 'modif_note' note.pk %}" class="card-link"> Modifier</a>
            <a href="{% url 'delete_note' note.pk %}" class="card-link"> Supprimer</a> 
        </div>  
    </div>
</div>




{% endblock content%}

note/templates/note/modif_note.html
{% extends 'base.html' %}
{% block title %}NotePad | Modification Note{% endblock title %}
{% block content %}


<div class="container">
  <div class="card mb-3 shadow">
      <div class="card-body">
          <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.media }}
              {{ form.as_p }}
              <button class="btn btn-primary btn-sm" > Modifier</button>
              <button class="btn btn-primary btn-sm" href= "{% url 'note' %}"> Annuler</button>
          </form>
      </div>  
  </div>
</div>

{% endblock content%}

note/templates/note/note.html
{% extends 'base.html' %}
{% block title %}NotePad | Note{% endblock title %}
{% block content %}

<hr>
<h1><center>MES NOTES</center></h1>
<hr>
<div class="container">
    <div class="row row-cols-md-3 row-cols-md-2">
         {% for note in object_list %}
            <div class= "col">
                <div class="card mb-3 shadow">
                    <div class="card-body">
                        <h3 class="card-title">{{note.title| safe }} -  <font size="3"> Le : {{note.creation_date | date:'d F Y'}}</font> </h3>
                        <p class="card-text">{{ note.content| safe | truncatechars:'200'}}</p>
                        <a href="{% url 'detail_note' note.id %}" class="card-link">Ouvrir</a>
                        <a href="{% url 'delete_note' note.pk %}" class="card-link">Supprimer</a>

                    </div>
                </div>
            
            </div>
        {% endfor%} 
        <style>
        
            .pagination a {
                border: 1px solid #ddd; /* Gray */
                color : white;
                padding-left : 8px;
                padding-right : 8px;
                background: #495057;
                font-size: 1.15rem;

          }
        </style>
        Page {{page_obj.number}} de {{page_obj.paginator.num_pages}}
        </div>
        <br>
        <ul style="ml: 10 px" class="pagination">
            {% if page_obj.has_previous%}
            <li><a href="?page=1" style="text-decoration:none"> Première  Page</a></li>
            <li><a href="?page={{ page_obj.previous_page_number }}" style="text-decoration:none">    Précédent  </a></li>
            {% endif %}
            {% if page_obj.has_next%}
            <li><a href="?page={{ page_obj.next_page_number }}" style="text-decoration:none"> Suivante  </a></li>

            <li><a href="?page={{ page_obj.paginator.num_pages }}" style="text-decoration:none">Dernière Page</a></li>
            {% endif %}
        </ul>
</div>


{% endblock content%}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>{% block title %} NotePad{% endblock title %} </title>
<!-- Bootstrap Icons--> 
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="icon" type="{% static 'images/x-icon' %}" href="images/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />        
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Lato&display=swap" rel="stylesheet">
<!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="{% static 'css/styles.css' %}"  />
    </head>

    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-2" id="mainNav">
            <div class="container px-4 px-lg-5">
            
                {% if user.is_authenticated %}
                        <a class="navbar-brand" href="{% url 'accounts:logout' %}">Déconnection</a>
                        <a class="navbar-brand" href="{% url 'accounts:profil' %}">Profil</a>
                {% else %}
                        <a class="navbar-brand" href="{% url 'accounts:login' %}">Me connecter</a>
                        <a class="navbar-brand" href="{% url 'accounts:register' %}">M'inscrire </a>
                {% endif %}
                
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link" href={% url 'pages:home' %}>Acceuil</a></li>
                        <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
                        <li class="nav-item"><a class="nav-link" href="pages:about">A propos</a></li>
                        
                        

                        {% if user.is_authenticated %}
                                <li class="nav-item"><a class="nav-link" href="#portfolio">Mes applications</a></li>
                        {% endif %}
                        
                        <li class="nav-item"><a class="nav-link" href="{% url 'pages:contact' %}">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        
        <header class="masthead">
            <div class="container px-4 px-lg-5 h-100">
                <div container>
<br>
    {% block content %}

    {% endblock content %}
    </div>
            </div>
        </header>
<!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container px-4 px-lg-5"><div class="small text-center text-muted">Copyright &copy; 2021 - Olivier Boutet</div></div>
        </footer>
        {% block bottom-scripts %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
<!-- SimpleLightbox plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
<!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<!-- * *                               SB Forms JS                               * *-->
<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        {% endblock bottom-scripts %}

    </body>
</html>

templates/pages/about.html
{% extends "base.html" %}
{% load static %}

{% block title %}NotePad | A propos{% endblock title %}
{% block content %}

  

{% endblock content %}

templates/pages/application.html
{% extends "base.html" %}
{% load static %}

{% block title %}NotePad | Applications{% endblock title %}
{% block content %}

  

{% endblock content %}

templates/pages/contact.html
{% extends "base.html" %}
{% load static %}

{% block title %}NotePad | Contact{% endblock title %}
{% block content %}

  

{% endblock content %}

templates/pages/home.html
{% extends "base.html" %}

{% block title %}NotePad | Homepage{% endblock title %}

<!-- Masthead-->
{% block content %}
<div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
    <div class="col-lg-8 align-self-end">
        {% if user.is_authenticated %}
            {% if user.first_name %}
                <h1 class="text-white font-weight-bold">Bienvenue {{ user.first_name | capfirst }} dans votre boîte à outils en ligne</h1>
            {% else %}
                <h1 class="text-white font-weight-bold">Bienvenue dans votre boîte à outils en ligne </h1><p class = "text-white">(pensez à complèter votre profil)</p>
            {% endif %}
        {% else %}
            <h1 class="text-white font-weight-bold">Bienvenue dans la boîte à outils en ligne</h1>
        {% endif %}
        <p>Aujourd'hui nous sommes le : {{myDate|date}}</p>
        <hr class="divider" / />
    </div>
    <div class="col-lg-8 align-self-baseline">
        <p class="text-white-75 mb-5">Ici vous trouverez vos outils de tous les jours dans un même conteneur : <br> Bloc-notes, Banques de mots de passe, Agenda, ...</p>
        <a class="btn btn-primary btn-xl" href="#about">Quelques apercus d'applications</a>
    </div>
</div> 
{% endblock content %}